version: '3.8'
services:
  backend:
    image: codenotary-be:2
    container_name: codenotary-be
    environment:
      - API_PORT=8000
      - VAULT_API_KEY=${VAULT_API_KEY}
      - VAULT_LEDGER = default
      - VAULT_COLLECTION = default
    network_mode: "host"
  frontend:
    image: codenotary-fe:2
    container_name: codenotary-fe
    environment:
      - REACT_APP_API_PORT=8000
    network_mode: "host"