version: '3.8'
services:
  backend:
    image: codenotary-be:1
    container_name: codenotary-be
    ports:
      - "8000:8000"
    environment:
      - API_PORT = 8000
      - VAULT_API_KEY=${VAULT_API_KEY}
      - VAULT_LEDGER = default
      - VAULT_COLLECTION = default
    network_mode: "host"
  frontend:
    image: codenotary-fe:1
    container_name: codenotary-fe
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_PORT = 8000
    network_mode: "host"